package Chap17;

import javax.print.attribute.ResolutionSyntax;
import java.io.*;
import java.util.Random;

public class Car implements Serializable,Comparable<Car>
{

    private String name,origin;
    private double mpg;
    private byte cylinders;
    private short hp,weight;        //Note that we are concentrating on cars don't expect weight to be above
                                    //27000 pounds.

    //private int mpg,cylinders,hp,weight;

    private static final int NAME_MAX_SIZE = 38;
    private static final int ORIGIN_MAX_SIZE = 9;


    public static final int REC_SIZE = NAME_MAX_SIZE + ORIGIN_MAX_SIZE
            + Double.BYTES + Byte.BYTES + 2 * Short.BYTES;

    private final int       NAME_POS=0,
                            MGP_POS=1,
                            CYL_POS=2,
                            HP_POS=3,
                            WEIGHT_POS=4,
                            ORIGIN_POS=5;

    /**
     * Constructor normalized for reads from a csv file
     * @param saVals
     */
    public Car(String[] saVals)
    {
        name= saVals[NAME_POS];
        mpg = Double.parseDouble(saVals[MGP_POS]);
        cylinders = Byte.parseByte(saVals[CYL_POS]);
        hp = Short.parseShort(saVals[HP_POS]);
        weight = Short.parseShort(saVals[WEIGHT_POS]);
        origin = saVals[ORIGIN_POS];
    }

    /**
     * Normal constructor for passing in values seperately
     * @param name
     * @param mpg
     * @param cylinders
     * @param hp
     * @param weight
     * @param origin
     */
    public Car(String name, double mpg, byte cylinders,short hp,short weight, String origin)
    {
        this.name = name;
        this.mpg = mpg;
        this.cylinders = cylinders;
        this.hp = hp;
        this.weight = weight;
        this.origin = origin;
    }

    /**
     * Default constructor
     */
    public Car()
    {
        //Accept the defaults for everything
    }

    //Autogenerated Getters
    //Note that we can return mosrt


    public String getName()
    {
        return name;
    }

    public String getOrigin()
    {
        return origin;
    }

    public double getMpg()
    {
        return mpg;
    }

    public byte getCylinders()
    {
        return cylinders;
    }

    public short getHp()
    {
        return hp;
    }

    public short getWeight()
    {
        return weight;
    }

    /**
     * Method for writing out attribute information to a given data output stream which is tied to
     * a file on the system.  This maintians the natural ordering which was supplied int the csv file
     * @param obOut
     * @throws IOException
     */
    public void writeToDatFile(DataOutputStream obOut) throws IOException
    {
        obOut.writeUTF(name);
        obOut.writeDouble(mpg);
        obOut.writeByte(cylinders);
        obOut.writeShort(hp);
        obOut.writeShort(weight);
        obOut.writeUTF(origin);
    }

    /**
     * Method for reading information from a given input stream.
     * This reliese on (1) The sequence for writing the information out as suppplied above and
     * (ii) The natural ordering of the assoicateid CSV file and the specific constructor that is designed
     * to accept attributes in that order.
     * @param obIn
     * @return
     * @throws IOException
     */
    public static Car readFromDataFile(DataInputStream obIn) throws IOException
    {
        return new Car(obIn.readUTF(),obIn.readDouble(),
                       obIn.readByte(),obIn.readShort(),
                       obIn.readShort(),obIn.readUTF());
    }


    @Override
    public String toString()
    {
        return String.format("Name %-22s MPG %-2.1f Cylinders %-3d HP %-5d Weight %-7d Origin %s",
                name,mpg,cylinders,hp,weight,origin);
    }

    /**
     * This method will write out all values in the attribute list to teh given random access file
     * as one frame packet
     * @param obRaf
     * @throws IOException
     */
    public void writeRecToRaf(RandomAccessFile obRaf) throws IOException
    {
        Utils.writeStringToRaf(name,obRaf,NAME_MAX_SIZE);
        obRaf.writeDouble(mpg);
        obRaf.writeByte(cylinders);
        obRaf.writeShort(hp);
        obRaf.writeShort(weight);
        Utils.writeStringToRaf(origin,obRaf,ORIGIN_MAX_SIZE);
    }

    public static Car readRecFromRaf(RandomAccessFile obRaf) throws IOException
    {
        String name = Utils.readStringFromRaf(obRaf, NAME_MAX_SIZE);
        double mpg = obRaf.readDouble();
        byte cylinder = obRaf.readByte();
        short hp = obRaf.readShort();
        short weight = obRaf.readShort();
        String sOrigin = Utils.readStringFromRaf(obRaf,ORIGIN_MAX_SIZE);
        return new Car(name,mpg,cylinder,hp,weight,sOrigin);
    }

    @Override
    public int compareTo(Car obOther)
    {
        return hp - obOther.getHp();
    }
}
